---
- hosts: all
  tasks:
  - name: Update cache & Full system update
    apt:
      update_cache: true

  - name: Install apache and dependencies
    apt:
      pkg:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql

  - name: Reload apache server
    command: systemctl restart apache2
